## Preprocessing

In [1]:
# Importing dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Importing and reading charity_data.csv
import pandas as pd
application_df = pd.read_csv('https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv')
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Dropping the non-beneficial ID columns 'EIN' and 'NAME'
application_df = application_df.drop(['EIN', 'NAME'], axis = 1)

In [3]:
# Determining the number of unique values in each column
unique_values = application_df.nunique()
print(unique_values)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Looking at APPLICATION_TYPE value counts to identify and replace with "Other"
application_type_value_counts = application_df['APPLICATION_TYPE'].value_counts()
print(application_type_value_counts)

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Creating a dataframe of the APPLICATION_TYPE value counts
application_type_value_counts_df = application_type_value_counts.reset_index()
application_type_value_counts_df.columns = ['APPLICATION_TYPE', 'count']
application_type_value_counts_df

   APPLICATION_TYPE  count
0                T3  27037
1                T4   1542
2                T6   1216
3                T5   1173
4               T19   1065
5                T8    737
6                T7    725
7               T10    528
8                T9    156
9               T13     66
10              T12     27
11               T2     16
12              T25      3
13              T14      3
14              T29      2
15              T15      2
16              T17      1

In [6]:
# Choosing a cutoff value and creating a list of application types to be replaced
# using the variable name 'application_types_to_replace'
filtered_application_type_value_counts_df = application_type_value_counts_df[application_type_value_counts_df['count'] < 16]
application_types_to_replace = filtered_application_type_value_counts_df['APPLICATION_TYPE'].tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app, 'Other')

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
T12         27
T2          16
Other       11
Name: count, dtype: int64

In [7]:
# Looking at CLASSIFICATION value counts to identify and replace with "Other"
classification_value_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_value_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [8]:
# Looking at CLASSIFICATION value counts >1
print(classification_value_counts[classification_value_counts > 1])

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [9]:
# Creating a dataframe of the CLASSIFICATION value counts
classification_value_counts_df = classification_value_counts.reset_index()
classification_value_counts_df.columns = ['CLASSIFICATION', 'count']
classification_value_counts_df

   CLASSIFICATION  count
0           C1000  17326
1           C2000   6074
2           C1200   4837
3           C3000   1918
4           C2100   1883
..            ...    ...
66          C4120      1
67          C8210      1
68          C2561      1
69          C4500      1
70          C2150      1

[71 rows x 2 columns]

In [10]:
# Choosing a cutoff value and creating a list of classifications to be replaced
# using the variable name 'classifications_to_replace'
filtered_classification_value_counts_df = classification_value_counts_df[classification_value_counts_df['count'] == 1]
classifications_to_replace = filtered_classification_value_counts_df['CLASSIFICATION'].tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls, 'Other')

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
Other       26
C8000       20
C7120       18
C1500       16
C6000       15
C1800       15
C1250       14
C8200       11
C1238       10
C1278       10
C1237        9
C1235        9
C7210        7
C1720        6
C2400        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C1267        2
C1256        2
C1234        2
C1246        2
C3200        2
Name: count, dtype: int64

In [11]:
# Converting categorical data to numeric with `pd.get_dummies`
application_df_dummies = pd.get_dummies(application_df)
application_df_dummies

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T3,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,False,False,False,True,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,False,False,False,True,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,False,False,False,True,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34295,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34296,1,5000,0,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,True,False
34297,1,5000,1,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34298,1,36500179,0,False,False,False,False,False,False,True,...,False,False,False,False,True,False,False,False,True,False

In [12]:
# Splitting preprocessed data into features and target arrays
y = application_df_dummies["IS_SUCCESSFUL"].values
X = application_df_dummies.drop(["IS_SUCCESSFUL"], axis = 1).values

# Splitting the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 1)

In [13]:
# Creating a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [14]:
# Checking the number of input features
print(len(X_train[0]))

87

## Compile, Train and Evaluate the Model

In [15]:
# Defining the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

# Starting with a single hidden layer
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 59                  # 2/3 the size of the input layer plus the output layer
# hidden_nodes_layer2 = __

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer1, input_dim = number_input_features, activation = 'relu'))

# Second hidden layer
# nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer2, activation = 'relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

# Checking the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 59)                5192

 dense_1 (Dense)             (None, 1)                 60

=================================================================
Total params: 5252 (20.52 KB)
Trainable params: 5252 (20.52 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [16]:
# Compiling the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [17]:
# Assignment prompt: "Create a callback that saves the model's weights every five epochs."

# Querying "How do I create a callback that saves a neural network model's weights every five epochs in Google Colab?"
# in ChatGPT yielded the following/the foundations for the following:

# Step 1: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Step 2: Import necessary libraries and define the custom checkpoint callback
from tensorflow.keras.callbacks import ModelCheckpoint

class CustomModelCheckpoint(ModelCheckpoint):
    def __init__(self, *args, **kwargs):
        self.epochs_since_last_save = 0
        self.period = kwargs.pop('period', 1)
        super().__init__(*args, **kwargs)

    def on_epoch_end(self, epoch, logs = None):
        self.epochs_since_last_save += 1
        if self.epochs_since_last_save >= self.period:
            self.epochs_since_last_save = 0
            super().on_epoch_end(epoch, logs)

# Define the custom checkpoint callback with period=5
checkpoint = CustomModelCheckpoint(
    filepath='/content/drive/My Drive/model_weights_epoch_{epoch:02d}.h5',    # Path in Google Drive
    save_weights_only = True,                                                 # Save only the weights
    period = 5                                                                # Save every 5 epochs
)

Mounted at /content/drive

In [18]:
# Training the model
fit_model = nn.fit(X_train_scaled, y_train, epochs = 50, callbacks = [checkpoint])

Epoch 1/50
804/804 [==============================] - 8s 7ms/step - loss: 0.5868 - accuracy: 0.7165
Epoch 2/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5595 - accuracy: 0.7292
Epoch 3/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5547 - accuracy: 0.7288
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5530 - accuracy: 0.7299
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5511 - accuracy: 0.7305
Epoch 6/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5498 - accuracy: 0.7313
Epoch 7/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5486 - accuracy: 0.7306
Epoch 8/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5487 - accuracy: 0.7321
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5472 - accuracy: 0.7331
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5466 - accuracy: 0.7330
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5464 - accuracy: 0.7322
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5457 - accuracy: 0.7333
Epoch 13/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5455 - accuracy: 0.7327
Epoch 14/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5446 - accuracy: 0.7313
Epoch 15/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5443 - accuracy: 0.7346
Epoch 16/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5436 - accuracy: 0.7338
Epoch 17/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5446 - accuracy: 0.7337
Epoch 18/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5434 - accuracy: 0.7350
Epoch 19/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5435 - accuracy: 0.7338
Epoch 20/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5428 - accuracy: 0.7351
Epoch 21/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5424 - accuracy: 0.7346
Epoch 22/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5430 - accuracy: 0.7343
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7347
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7358
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7350
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7347
Epoch 27/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5416 - accuracy: 0.7345
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7353
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7348
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7352
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7361
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7353
Epoch 33/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5407 - accuracy: 0.7346
Epoch 34/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5402 - accuracy: 0.7356
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7362
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7352
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7370
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7374
Epoch 39/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5395 - accuracy: 0.7359
Epoch 40/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5391 - accuracy: 0.7362
Epoch 41/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5393 - accuracy: 0.7362
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7368
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7362
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7369
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7362
Epoch 46/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5388 - accuracy: 0.7362
Epoch 47/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5385 - accuracy: 0.7373
Epoch 48/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5384 - accuracy: 0.7364
Epoch 49/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5381 - accuracy: 0.7359
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7373

In [19]:
# Evaluating the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose = 2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 2s - loss: 0.5541 - accuracy: 0.7320 - 2s/epoch - 8ms/step
Loss: 0.554085910320282, Accuracy: 0.7320116758346558

In [20]:
# Exporting the model to HDF5 file
nn.save('/content/drive/My Drive/AlphabetSoupCharity.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(